#!/bin/bash

echo -e "\e[0;32m"
echo -e "|"
echo -e "|"
echo -e "|              __"
echo -e "______________(_ \ "
echo -e "|               \ \ "
echo -e '|                (")'
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|_______________________________________________"
echo -e "\e[0m"
