#!/bin/bash

echo -e "\e[0;32m"
echo -e "|"
echo -e "|"
echo -e "|"            
echo -e "________________"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|               _"
echo -e "|              ( \ "
echo -e "|               ) )"
echo -e '|              ("/ '
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|_______________________________________________"
echo -e "\e[0m"
