#!/bin/bash

echo -e "\e[0;32m"
echo -e "|"
echo -e "|"
echo -e "|"            
echo -e "________________"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|"
echo -e "|           \.|\/|./ "
echo -e "|____________\    /_____________________________"
echo -e "\e[0m"
